---
abstract: 'A POE-based parser to parse text into an array of tokens.'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.89'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Filter-ParseWords
no_index:
  directory:
    - examples
    - inc
    - t
provides:
  POE::Filter::ParseWords:
    file: lib/POE/Filter/ParseWords.pm
    version: 1.06
requires:
  POE: 0.38
  POE::Filter: 0
  Text::ParseWords: 0
  perl: 5.6.0
resources:
  homepage: http://github.com/bingos/poe-filter-parsewords/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/poe-filter-parsewords.git
version: 1.06
